### ISSUE TITLE
always has this error

### ISSUE THREAD

**Issue by srwgin** [mauzel/mproxy-gbf#1]
Exception happened during processing of request from ('::1', 58139, 0, 0)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\temp\mproxy-gbf-master\gbfproxy\handlers.py", line 65, in __init__
    super(GBFCachingHandler, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

**Comment by mauzel** [comment]
This error basically means that your browser closed a connection before data was fully loaded.

e.g. You changed pages before everything fully loaded.

It's harmless, but I will silence that error message soon.
